# This image attempts to mirror the currently-active RopeWiki server as closely
# as practical while installing from canonical sources.

# To build this image, run this in this folder:
#   docker image build -f Dockerfile_legacy -t ropewiki/legacy_webserver .

FROM ubuntu:14.04

# === Install services and tools ===

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update

# Install nginx
RUN apt-get install -y --no-install-recommends nginx

# Install php
# Don't start the php service after installation
# https://stackoverflow.com/a/48782486/651139
RUN printf '#!/bin/sh\nexit 0' > /usr/sbin/policy-rc.d
RUN apt-get install -y --no-install-recommends php5-fpm php5-cli

# Install various tools
RUN apt-get install -y --no-install-recommends wget unzip git nano

# Install composer
COPY ./scripts /root
RUN /root/install_composer.sh
RUN mv composer.phar /usr/local/bin/composer

# === Install MediaWiki ===

# Retrieve MediaWiki installation package
RUN wget https://releases.wikimedia.org/mediawiki/1.24/mediawiki-core-1.24.1.tar.gz

# Follow installation instructions:
# https://phabricator.wikimedia.org/source/mediawiki/browse/REL1_25/INSTALL
RUN tar xvzf mediawiki-core-1.24.1.tar.gz
RUN mv mediawiki-1.24.1 /usr/share/nginx/html/ropewiki

# Configure quick symlink
RUN ln -s /usr/share/nginx/html/ropewiki /rw

# === Customize site (including custom extensions) ===

# Copy in our MediaWiki customizations
COPY ./html /usr/share/nginx/html

# Copy in our nginx customizations
COPY ./nginx /etc/nginx

# === Install composer-specified extensions ===

RUN cd /rw && composer install

# Install SemanticMediaWiki 2.1
# https://web.archive.org/web/20150314234734/http://semantic-mediawiki.org/wiki/Help:Installation
# TODO: Finish installation process

# === Install extensions via git ===

# Note: we can't use gerrit.wikimedia.org because they apparently use a cipher
# that isn't supported in Ubuntu 14, and there don't appear to be any gnutls
# backports to fix that.  See:
# https://github.com/NVIDIA/nvidia-docker/issues/714#issuecomment-386244620

RUN cd /rw/extensions && git clone https://github.com/SemanticMediaWiki/SemanticCompoundQueries.git && cd SemanticCompoundQueries && git checkout f5eed72
RUN cd /rw/extensions && git clone https://github.com/wikimedia/mediawiki-extensions-SemanticDrilldown SemanticDrilldown && cd SemanticDrilldown && git checkout a569de7
RUN cd /rw/extensions && git clone https://github.com/RopeWiki/SemanticFormsInputs.git && cd SemanticFormsInputs && git checkout e8254cf
RUN cd /rw/extensions && git clone https://github.com/wikimedia/mediawiki-extensions-SemanticRating SemanticRating && cd SemanticRating && git checkout 3af01d6
RUN cd /rw/extensions && git clone https://github.com/wikimedia/mediawiki-extensions-CategoryTree CategoryTree && cd CategoryTree && git checkout 52c3eb7
RUN cd /rw/extensions && git clone https://github.com/wikimedia/mediawiki-extensions-CheckUser CheckUser && cd CheckUser && git checkout 99f4a22
RUN cd /rw/extensions && git clone https://github.com/wikimedia/mediawiki-extensions-ContributionScores ContributionScores && cd ContributionScores && git checkout 7e02f8a
RUN cd /rw/extensions && git clone https://github.com/wikimedia/mediawiki-extensions-Nuke Nuke && cd Nuke && git checkout 0d4bfb5
RUN cd /rw/extensions && git clone https://github.com/wikimedia/mediawiki-extensions-UserMerge UserMerge && cd UserMerge && git checkout 22c450d
RUN cd /rw/extensions && git clone https://github.com/wikimedia/mediawiki-extensions-Arrays Arrays && cd Arrays && git checkout f28592b
RUN cd /rw/extensions && git clone https://gitlab.com/HydraWiki/extensions/embedvideo.git EmbedVideo && cd EmbedVideo && git checkout bdc2cf1
RUN cd /rw/extensions && git clone https://github.com/wikimedia/mediawiki-extensions-MagicNoCache MagicNoCache && cd MagicNoCache && git checkout a6aac2c
RUN cd /rw/extensions && git clone https://github.com/wikimedia/mediawiki-extensions-MyVariables MyVariables && cd MyVariables && git checkout 70cf94b
RUN cd /rw/extensions && git clone https://github.com/wikimedia/mediawiki-extensions-Scribunto Scribunto && cd Scribunto && git checkout 10abeb5
RUN cd /rw/extensions && git clone https://github.com/wikimedia/mediawiki-extensions-UrlGetParameters UrlGetParameters && cd UrlGetParameters && git checkout 68afd03
RUN cd /rw/extensions && git clone https://github.com/wikimedia/mediawiki-extensions-Variables Variables && cd Variables && git checkout 6f4bbd0
RUN cd /rw/extensions && git clone https://github.com/wikimedia/mediawiki-extensions-PdfHandler PdfHandler && cd PdfHandler && git checkout 5e29202
RUN cd /rw/extensions && git clone https://github.com/wikimedia/mediawiki-extensions-googleAnalytics googleAnalytics && cd googleAnalytics && git checkout ce5ef02

# TODO: finish installation and configuration to match current deployed configuration

# To explore the system to see how things have been set up, following building:
#   docker container run -it ropewiki/legacy_webserver

# TODO: set up appropriate services to start and then run something that keeps the container active

# /etc/php5/fpm/php-fmp.conf
